#!/usr/bin/env ruby
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require 'fileutils'

file = "" + ARGV[0]
file.gsub!(/failed_/, '')

new_file = File.expand_path(File.join(File.dirname(__FILE__), "../failed_#{file}"))
approved_file = File.expand_path(File.join(File.dirname(__FILE__), "../test_data/#{file}"))
if !File.exist?(new_file)
  puts "#{new_file} does not exist"
  exit 1
end

FileUtils.mv new_file, approved_file
puts "Approved #{file}"
