#!/usr/bin/env ruby
APP_ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

require 'fileutils'

new_file = File.expand_path(File.join(File.dirname(__FILE__), "../tmp/project/#{ARGV[0]}"))
approved_file = File.expand_path(File.join(File.dirname(__FILE__), "../test_data/#{ARGV[0]}"))
if !File.exist?(new_file)
  puts "#{new_file} does not exist"
  exit 1
end

FileUtils.cp new_file, approved_file
puts "Approved #{ARGV[0]}"
